{
	"types": {
		"Place": {
			"pluralLabel": "Places"
		}
	},

	"items": [
		{
			"type": "Place to Visit",
			"label": "Temple of the Tooth Relic",
			"Type" : "Historical and Heritage",
			"SubCategory" : "", 
			"Province": "Central Province",
			"District": "Kandy District",
			"City": "Kandy",
			"Address": "Sri Dalada Veediya, Kandy",
			"Contact No": "+94 812234226",
			"Description": "The Temple of the Tooth Sri Lanka popularly known as the “Sri Dalada Maligawa” is one of the most picturesque and iconic Buddhist temples in the country and is a prominent itinerary item in the list of Kandy things to do. Built in the year 1595 during the reign of King Vimaladarmasuriya I, the temple houses the sacred tooth relic of Lord Buddha and therefore is venerated by devotees of the Buddhist faith from all corners of the world.\n\nAttracting crowds of white-clad pilgrims bearing lotus flowers for means of worship, the Maligawa features a myriad of intricate carvings that speak volumes of the architectural values of Kandy. Named “Mahawahalkada”, the main entrance gates run over the moat and visitors will be awed by the “Sandakada Pahana” or the elaborate moonstone found at the foot of these gates.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "1500 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "5.30 a.m. to 8.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Meemure",
			"Type" : "Nature and WildLife",
			"SubCategory" : "Forests and Wild Life",
			"Province": "Central Province",
			"District": "Kandy District",
			"City": "Kandy",
			"Address": "Meemura Road, Kaikawala",
			"Contact No": "",
			"Description": "Meemure is an isolated village in the Central Province of Sri Lanka, located 324m above sea level and hidden amongst the mountains. The only way to reach it is from the  ‘Hunnasgiriya’ mountain, which is part of the Knuckles range, approximately 50km from Kandy. It’s a difficult trail of 33km from Hunnasgiriya to Meemure with many tricky spots, though the view along it is excellent. The village itself receives abundant water in the form of waterfalls that have their sources in the evergreen forests of the Knuckles. East of the village lies the pyramid shaped Lakegala mountain; while the west is dominated by the picturesque Knuckles range. The northern boundary of Meemure borders a forest which runs to the ‘Pitawala Pathana’ grassland; and the south is bounded by Heen River.\n\nPack-bulls used to be the solitary method of transport to Meemure until 2004. Herds of cattle carried sacks full of goods and equipment to the village. Due to the fertility and prosperity of the village; the pack-bulls were only used to carry salt, cloths, tobacco and calcium bicarbonate. But with the invasion of modern technology, the trails have been widened to allow three wheelers, jeeps and small trucks.",
			"VisitingDuration": "6 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 Hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Embekke Devalaya",
			"Type" : "Historical and Heritage",
			"SubCategory" : "",
			"Province": "Central Province",
			"District": "Kandy District",
			"City": "Embekka",
			"Address": "6H99+53G, Embekka Pilimatalawa Road, Embekka",
			"Contact No": "+94 71 762 8870",
			"Description": "The Embekka Devalaya (Embekke or Embekka) Temple is situated in an area known as Udunuwara in the Kandy district. It was built during the Gampola Era (AD1357 – 1374) by King Vikramabahu lll, as a place of worship dedicated to Mahasen, also known as “Katharagama Deviyo”. It is also where local deity Devatha Bandara is worshipped by devotees.",
			"VisitingDuration": "1 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "300 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Cormorant Kitulgala Adventure Sports ",
			"Type" : "Adventure and Sports",
			"SubCategory" : "Inland Water Sports",
			"Province": "Sabaragamuwa Province",
			"District": "Kegalle District",
			"City": "Kithulgala",
			"Address": "Kitulgala, Sri Lanka",
			"Contact No": "+94 718244574",
			"Description": "CORMORANT is a Adventure sports located in Sri Lanka. It is one of the 73 Adventure sportses in Sri Lanka. Address of CORMORANT is Kitulgala, Sri Lanka.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "7 a.m. - 5.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Kitulgala Adventure Sports",
			"Type" : "Adventure and Sports",
			"SubCategory": ["Inland Water Sports","Camping"],
			"Province": "Sabaragamuwa Province",
			"District": "Kegalle District",
			"City": "Kithulgala",
			"Address": "Adventure Sports Center, Kitulgala, Sri Lanka",
			"Contact No": "+94 773 595411",
			"Description": "Kitulgala is located in the west of Sri Lanka and is one of the wettest towns in the country. The climate is humid throughout the year, which makes it an ideal destination for white-water rafting and other water-based adventure sports. We take pride providing you with the most unique experiences while ensuring your safety. Every adventure is carefully planned according the high standards we adhere to in sustainability and responsible travelling.",
			"VisitingDuration": "3.5 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.30 a.m. - 4.30 p.m. Daily"
		},
		
		{
			"type": "Place to Visit",
			"label": "Ceylon Adventure Sports",
			"Type" : "Adventure and Sports",
			"SubCategory": ["Inland Water Sports","Camping","Rock Climbing,Mountain Trekking and Hiking"],
			"Province": "Sabaragamuwa Province",
			"District": "Kegalle District",
			"City": "Kithulgala",
			"Address": "Belilena Junction, Kitulgala, Sri Lanka",
			"Contact No": "+94 777 83 64 46",
			"Description": "Offering a garden and barbecue, Ceylon Adventure Sports & Resort is located in Kitulgala. There is a restaurant and guests can have fun at the water park.",
			"VisitingDuration": "3 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8:30 a.m. –4:30 p.m.  Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Avant Leisure (Pvt) Ltd",
			"Type" : "Adventure and Sports",
			"SubCategory": "Adventure Sports",
			"Province": "Western Province",
			"District": "Colombo District",
			"City": "Sri Jayawardenapura Kotte",
			"Address": "No. 613, Bangalawa Junction, Kotte Rd, Sri Jayawardenepura Kotte",
			"Contact No": "+94 112 053 140",
			"Description": "Avant Leisure (Pvt) Ltd  offers creative and innovative ideas to allow the maximum enjoyment of the adventure sports,  providing an excelent service , with the backing of skilful professionals  in the field of tourism.  We own the hight quality equipment in Sri Lanka.\n\nAvant Leisure offers a range of adventure sports in Sri Lanka with the latest equipment to give our customers the best enjoyment. Avant Leisure consists of Jet Skis, Speed Boats, Luxury boats, Para Sailing, Para Triking, Para Motoring, Wind Surfing, ATV quad bikes and more. We focus on providing the best variety of adventure sports in Sri Lanka and to attract customers to be a part of a once in a life time experience.",
			"VisitingDuration": "3 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "Monday to Friday  : 9.00 a.m. –5:30  p.m.  \nSaturday : 9.00 a.m.– 2.00 p.m.\nSunday Closed"
		},
		{
			"type": "Place to Visit",
			"label": "Colombo Dunes ATV Track - Crate Adventure",
			"Type" : "Adventure and Sports",
			"SubCategory": "ATV Track",
			"Province": "Western Province",
			"District": "Colombo District",
			"City": "Colombo",
			"Address": "Crate Adventure (Pvt) Ltd, Colombo Dunes ATV, Port City, Colombo 01.",
			"Contact No": "+94 71 772 7777",
			"Description": "Experience ATV riding, Kayaking, Trekking along with a beautiful stay at our Panoramic Glass Cabin just 45 minutes from Colombo",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.30 a.m. - 7.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "St Joseph’s Chapel",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Galle",
			"Address": "Lighthouse Street, Galle Dutch Fort",
			"Contact No": "",
			"Description": "This tiny chapel has absorbed in every wall ounce of serenity to impart to visitors looking for inner peace. St. Joseph’s Chapel is a depiction of the Roman Catholics from the Portuguese times, which was later revived by the Dutch. You will observe a tint of Dutch architectural style in this quaint chapel. Spending some quality along time inside this holy building attracts a lot of peace.",
			"VisitingDuration": "0.5 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "08.30 a.m. to 05.30 p.m.  Daily"
		},
		{
			"type": "Place to Visit",
			"label": "St. Mary's Cathedral",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Galle",
			"Address": "Galle",
			"Contact No": "+94 912 222 490",
			"Description": "This Cathedral is for the Roman Catholic Diocese living in this part of the country and is one of the best tourist places in Galle. With the growth of other religions in the region, the Bishops in 1983 took the call of having a place for the diocese to have a place to pray. This church prays to the Blessed Virgin Mary and is visited by the Catholics living in the south of Sri Lanka. St. Mary’s Cathedral is proudly titled as the landmark of this city.",
			"VisitingDuration": "0.45 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "6.00 a.m. to 7.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Galle Dutch Fort",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Galle",
			"Address": "65a Lighthouse St, Fort, Galle",
			"Contact No": "+94-912232568",
			"Description": "The Galle Fort, or Dutch Fort as it is also known, is a fortification first built by the Portuguese on the Southwestern coast of Sri Lanka. The initial fortifications, which were built in the late 16th century, were quite basic. However, the fort underwent extensive modifications in the 17th century by the Dutch, making it one of the most important archeological, architectural and historic monuments to illustrate the European influence in South East Asia between the 16th and 19th centuries. According to a statement by UNESCO, the site was recognized as a World Heritage Site for its unique exposition of an urban ensemble which illustrates the interaction of European architecture and South Asian traditions from the 16th to the 19th centuries which is criterion number four for such recognition.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "2500 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "Galle Fort - 24 Hours Daily\nNational Maritime Museum – 9:00 a.m. to 7:00 a.m. (Sat-Wed)\nNational Museum – 9:00 a.m. to 5:00 a.m. (Wed-Sun)\nGalle Fort Ramparts – Around 5:00 p.m.\nDutch Reformed Church – Anytime."
		},
		{
			"type": "Place to Visit",
			"label": "Galle Harbour",
			"Type" : "Nature and WildLife",
			"SubCategory": "Sea and Coastal Areas",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Galle",
			"Address": "Galle",
			"Contact No": "",
			"Description": "This natural harbour that has remained in existence for two thousand years now, is one of the best places to visit in Galle. The activity on this port is high and it serves as the regional port in Sri Lanka. Galle Harbour is amongst the very few places that support people who want to spend time on their yachts for it has been recognized as one of the best places to do so by the International Yacht Societies.\n\nA popular attraction on the Galle Harbour is to watch people at work and to see the inscription in three languages left behind by a Chinese man many years ago.",
			"VisitingDuration": "1 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 Hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Meeran Jumma Mosque",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Galle",
			"Address": "90 Leyn Baan St, Galle 80000",
			"Contact No": "",
			"Description": "Built logically facing the angle of Mecca, the Meeran Jumma Mosque is another structure that demands an alluring visit when walking around the Galle Fort lanes. The inside of the mosque is sheer beauty of well-done Italian flooring, arresting chandeliers, artistic glasses and huge corridors which puts this mosque on a ‘must-see’ list of places to visit in Galle. \n\nDevotees spend some time outside on the lawn as they watch the mosque in awe of its charm. The mosque allows even the women to enter provided they are dressed decently. In the latest renovations, they even added another prayer room only for the women.",
			"VisitingDuration": "0.5 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "4.30 a.m. to 10.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Unawatuna Beach",
			"Type" : "Nature and WildLife",
			"SubCategory": "Sea and Coastal Areas",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Unawatuna",
			"Address": "Unawatuna",
			"Contact No": "",
			"Description": "A beach with golden sand that complements the clear ocean waves is surely one of the places to visit in Galle during your trip. Lying in the southern region of Sri Lanka, Unawatuna Beach is one of the most famous spots amongst tourists for swimming, walking and relaxing. \n\nOne can also rent some sunbeds to take the day off from the world and just lay still as you oversee the vast sea. This beach is surrounded by a lot of eateries that surely put a fine cap on a well-spent day. Canoeing is a great pastime on this beach",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "20 LKR",
			"Ticket Value - Foriegner": "100 LKR",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 Hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Jungle Beach",
			"Type" : "Nature and WildLife",
			"SubCategory": "Sea and Coastal Areas",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Unawatuna",
			"Address": "Rumassala,Unawatuna",
			"Contact No": "",
			"Description": "The Jungle Beach is an out-of-the-way and serene beach that is a storehouse of all the quiet time you need on your holiday. Located a little ahead of the Japanese Peace Pagoda, this Beach is one of the most relaxed one and is much less swarming than all the other tourist places in Galle. \n\nYou can sit back on the sandy beach and get a perfect tan, or swim in the clear waters that seem like a mirror image of the ground below. If you are a fan of the aquatic life, then you could spend some time Snorkeling to see for yourself the life of the rich marine life in Galle.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "False",
			"Accesibility by Vehicle": "True",
			"Opened Hours": "24 Hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Japanese Peace Pagoda",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Unawatuna",
			"Address": "Jungle Beach Rd, Unawatuna",
			"Contact No": "",
			"Description": "The Japanese Peace Pagoda is for all those people who are looking for inner peace and some time for introspection. This tranquil structure built not so long ago is perched on top of the Rumassala Hill from where you can see the expansive ocean and the thick jungles. Take a deeper dip into this composure and attend the daily ritual that they perform every evening at 05.30 p.m. \n\nThe construction is tall enough to be visible for people standing on the Unawatuna Beach and Galle Beach. The aura at dusk is fascinating and rides one into another world of beauty.",
			"VisitingDuration": "0.75 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "07.00 a.m. to 09.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Sea Turtle Hatchery",
			"Type" : "Nature and WildLife",
			"SubCategory": ["Sea and Coastal Areas"],
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Hikkaduwa",
			"Address": "Sea Turtle Hatchery and Rescue Center A2, Hikkaduwa, Sri Lanka",
			"Contact No": "+94 77 293 8338",
			"Description": "Some people of Sri Lanka have dedicated their lives to animals around the Seas, and the Sea Turtle Hatchery is run by one such family. Every member is steadfast towards helping out the sea turtles who need medical help, or those who are pregnant.\n\nIn fact, they even help the sea turtles breed, and provide them with a safe environment to lay their eggs and care for them. The reason why it is one of the best places to visit in Galle is that, you will get to witness all of that at once during a short detour to this turtle abode.",
			"VisitingDuration": "1 Hours",
			"Ticket Value - Local": "500 LKR",
			"Ticket Value - Foriegner": "500 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "07.30 a.m. to 06.00 p.m."
		},
		{
			"type": "Place to Visit",
			"label": "Poseidon Diving Station Hikkaduwa",
			"Type" : "Adventure and Sports",
			"SubCategory": "Sea Water Sports",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Hikkaduwa",
			"Address": "Poseidon Diving Station,\nGalle Road,\nHikkaduwa",
			"Contact No": "+94 912277294",
			"Description": "Since 1973 Poseidon has been diving and teaching in the waters around Sri Lanka. With over 40 years experience we have built up the best reputation for safety in diving, professionalism and friendliness. Our five star dive center offers a range of diving experiences, from try dives and the beginner’s PADI Open Water Diver course up to instructor development courses.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.00 a.m. - 8.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Dive Seenigama Dive Lanka",
			"Type" : "Adventure and Sports",
			"SubCategory": "Sea Water Sports",
			"Province": "Southern Province",
			"District": "Galle District",
			"City": "Hikkaduwa",
			"Address": "Dive Seenigama, Dive Lanka,\nGalle Road, Seenigama,\nHikkaduwa",
			"Contact No": "+94  91 4 943 659",
			"Description": "Dive Seenigama, Dive Lanka also known as Dive For Good: allows you to discover the fantastic sea life, coral reefs, and ship wrecks that Southern coast of Sri Lanka offers while supporting the local rural community of Seenigama and the surrounding areas.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "08.00 a.m. - 8.30 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Flying Ravana Adventure park",
			"Type" : "Adventure and Sports",
			"SubCategory": ["Adventure Sports","ATV Track","Zip Linning"],
			"Province": "Uva Province",
			"District": "Badulla District",
			"City": "Ella",
			"Address": "98 ADVENTURES PVT LTD\nUva Greenlands Estate, Passara Road, Ella",
			"Contact No": "+94 57 493 0000",
			"Description": "Flying Ravana Adventure park is one of a kind experience available in Sri Lanka, located amidst the luscious green estates of Ella. Completed with its pride, Sri Lanka’s first-ever Mega zip-line.\nThe two-wire zip-line stretches for more than half a kilometer, slides at 80kmph, and offers a bird’s-eye view of the beautiful hills of the island.\nThe adventure park is exclusively designed for adventure enthusiasts and adrenaline junkies who prefer a not-so-ordinary hillside experience, offering ATV/quad bike rides, Abseiling, Archery, and Air rifling for a gripping outdoor experience.",
			"VisitingDuration": "5 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.30 a.m. - 5.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Colombo Mountain ATV Track - Crate Adventure",
			"Type" : "Adventure and Sports",
			"SubCategory": "ATV Track",
			"Province": "Western Province",
			"District": "Gampaha District",
			"City": "Gampaha",
			"Address": "Crate Adventure (Pvt) Ltd\nColombo Mountain\nMaligathenna Rd \nButhpitiya\nGampaha",
			"Contact No": "+94 71 772 7777",
			"Description": "Experience ATV riding, Kayaking, Trekking along with a beautiful stay at our Panoramic Glass Cabin just 45 minutes from Colombo",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "9.00 a.m. - 5.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Colombo Divers Diving Center",
			"Type" : "Adventure and Sports",
			"SubCategory": "Sea Water Sports",
			"Province": "Western Province",
			"District": "Gampaha District",
			"City": "Negombo",
			"Address": "47, Palangathure West\nNegombo",
			"Contact No": "+94 77 736 7776",
			"Description": "SSI & PADI Courses - Specialty training and advanced courses- Fun Dive Trips",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8:00 a.m. – 7:00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Wasgamuwa National Park",
			"Type" : "Nature and WildLife",
			"SubCategory": ["Forests and Wild Life ","Safari"],
			"Province": "North Central Province",
			"District": "Polonnaruwa District",
			"City": "Polonnaruwa",
			"Address": "QW3C+78R, Nuwaragala",
			"Contact No": "+94 663 669 046",
			"Description": "The Wasgamuwa National Park is located in the Sri Lankan districts of Matale and Polonnaruwa. The natural park is about 225 kilometres away from the capital city of Colombo with the nearest town being Polonnaruwa. Wasgamuwa is spread over a sprawling 36,900 hectares, surrounded by River Amban Ganga and River Mahaweli Ganga on the eastern and western sides of the National Park. In the year of 1938, some parts of the park were declared as ‘Strict Nature Reserves’ after which the surrounding areas were also pulled in, that is how the whole park that is now spread over a humongous area of 36,900 hectares came to be known as, the Wasgamuwa National Park in 1984.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "6.00 a.m. to 6.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Aluvihara Rock Cave Temple",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Matale",
			"Address": "Trincomalee road, Matale, Sri Lanka",
			"Contact No": "+94 662 222 533",
			"Description": "Aluvihare Rock Temple (also called Matale Alu Viharaya) is a sacred Buddhist temple located in Aluvihare, Matale District of Sri Lanka. Surrounded by hills, the Aluvihara cave temple is situated 30 km north of Kandy on the Matale-Dambulla road. The history of Aluvihare Rock Temple is traced back to the 3rd Century B.C to the reign of King Devanampiyatissa. It is believed that the King built the dagoba, planted the Bo sapling and founded the temple after the introduction of Buddhism to the country during his reign.\n\nAluvihare Rock Temple was the historic location where the Pāli Canon was first known to be written down completely in the text on ola (palm) leaves. Many monastery caves, some of which exhibit frescoes are situated near this temple.",
			"VisitingDuration": "1 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Hunnasgiriya Water Fall",
			"Type" : "Nature and WildLife",
			"SubCategory": "Lakes Rivers and WaterFalls",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Elkaduwa",
			"Address": "Elkaduwa,Matale",
			"Contact No": "+94 71 343 9383",
			"Description": "Hunnasgiriya Water Fall is a man-made waterfall that belongs to the hotel which has the same name. Above the falls, there are 32 hectares of land consisting of an artificial lake and that too belongs to the hotel. This beautiful waterfall is fed by a stream from the nearby mountain peak named “Hunnasgiriya mountain”. Hunnasgiriya waterfall resides\n\n At the center of Hunnasgiriya Estate and this particular area faces every climate condition in the country. The drive towards this waterfall is a very scenic one that offers many beautiful views around the area. Though the nearby hotel is quite popular among honeymoon couples, having this beautiful waterfall in the vicinity with a breathtakingly beautiful mountain view invites local as well as foreign travelers alike to come and enjoy the unspoiled beauty of Sri Lanka.   The woods around the waterfall is home to many kinds of trees that are special to Sri Lanka as well as it is also a sanctuary for a variety of wildlife and flora. Before you visit this beauty, remember to inquire about the rainfall in the area, since the waterfall may have lesser water in the dry season. Even with less water, the waterfall is still beautiful with its’ surrounding nature and this place is a highlight in the Kandy district, which definitely makes it a must-visit destination in Sri Lanka.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "No",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "sembuwatta lake",
			"Type" : "Nature and WildLife",
			"SubCategory": "Lakes Rivers and WaterFalls",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Elkaduwa",
			"Address": "Elkaduwa,Matale",
			"Contact No": "+94 66 493 5767",
			"Description": "Sembuwatta Lake is a tourist attraction situated at Elkaduwa in the Matale District of Sri Lanka, adjacent to the Campbell's Lane Forest Reserve. Sembuwatta Lake is a man-made lake created from natural spring water. Alongside the lake is a natural swimming pool. Sembuwatta Lake is believed to be 9 m to 12 m deep.",
			"VisitingDuration": "3 Hours",
			"Ticket Value - Local": "200 LKR",
			"Ticket Value - Foriegner": "1000 LKR",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "No",
			"Opened Hours": "9.00 a.m. - 5.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Bambarakiri Ella Falls",
			"Type" : "Nature and WildLife",
			"SubCategory": "Lakes Rivers and WaterFalls",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Rattota",
			"Address": "B274, Matale Laggala Road, 21406",
			"Contact No": "",
			"Description": "This magnificent waterfall is situated close to Rattota town in Matale District. Take Matale – Ilukumbura road to the Bamarakiri Falls bend, which is 1km past Rattota town, where the fall is to be found. The Bambarakiri Falls is 18km from Matale town. The Bambarakiri Falls is located approximately 40km away from our Amaya Hunas Falls, one of the most popular honeymoon hotels in Sri Lanka.\n\nThe fall is set amidst the mesmerizing greenery of the Knuckles mountain range. Bambarakiri Ella is a fall of 10m. The fall can be viewed in three parts. Different varieties of butterflies and birds come to the area of the falls mostly in clear mornings making the view even more charming.\n\nA very old-fashioned suspension bridge extends over the falls adding an enchanting touch to the already beautiful scene.\n\nGallons of water come crashing down to earth at a high speed. The rock pool at the base of the waterfall is safe for a dip during the dry summer, but can be very dangerous during heavy rainy season.",
			"VisitingDuration": "1 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "No",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Arangala Mountain Peak",
			"Type" : "Nature and WildLife",
			"SubCategory": "Mountains",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Naula",
			"Address": "Naula,Matale",
			"Contact No": "",
			"Description": "Arangala mountain in the Naula Divisional Secretariat Division is another mountain range with a rough slope that is related to that historical background.\n\nAn isolated pillar-like structure can be seen at the top of Arangala Hill. Many legends associated with it still exist in the villages around Naula. Mysterious events and constructions as well as notes are unique to Arangala Rock.\n\nAnother important place to meet along the way while climbing Arangala Kanda are the ancient caves. Designed to accommodate a variety of occasions, these caves are completely natural locations. Above these caves is a pile of rocks that hold the reeds in place.\n\nVisitors to the top of Arangala Kanda can easily see a 360 degree view. It was a truly amazing sight. From the top of the rock you can see the Matale region, Kandy region, Wheelshire, Atipola and Brandigala rocks, Ambokka as well as the entire Knuckles region and Mount Rivaston.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "True",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Coconut Tree Hill",
			"Type" : "Nature and WildLife",
			"SubCategory": "Sea and Coastal Areas",
			"Province": "Southern Province",
			"District": "Matara District",
			"City": "Mirissa",
			"Address": "WFQ9+M7X, Mirissa",
			"Contact No": "",
			"Description": "This is one of the prettiest, very Instagram-worthy spots on the South. It is situated at the end of Mirissa Beach and completely covered with coconut trees overlooking the ocean.",
			"VisitingDuration": "0.5 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "True",
			"Opened Hours": "24 hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Mirissa Water Sports",
			"Type" : "Adventure and Sports",
			"SubCategory": "Sea Water Sports",
			"Province": "Southern Province",
			"District": "Matara District",
			"City": "Mirissa",
			"Address": "Mirissa Water Sports (Pvt) Ltd\n Senasuma, Harbour Road,\n Mirissa",
			"Contact No": "+94 77 3597732",
			"Description": "Whale and dolphin watching is the premier activity of Mirissa Water Sports (MWS). We are the first and longest established whale-watching operator on the south coast of Sri Lanka.",
			"VisitingDuration": "2.5 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.00 a.m. - 5.00 p.m. Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Gregory Lake",
			"Type" : "Nature and WildLife",
			"SubCategory": "Lakes Rivers and WaterFalls",
			"Province": "Central Province",
			"District": "Nuwara Eliya District",
			"City": "Nuwara Eliya",
			"Address": "Nuwara-Eliya, Sri Lanka",
			"Contact No": "",
			"Description": "In the heart of hill country, Gregory Lake is a extremely popular place with both foreign tourists and locals. This is a place to enjoy cool weather. Gregory Lake, is a reservoir in hill city, Nuwara-Eliya, Sri Lanka. Lake Gregory was built by Governor William Gregory between 1872 and 1877.  The park near the lake gives you various activities such speed boat, swan boats, dinky boats, Pony ride and many more. There is also a bicycle path around the lake. Bicycle cost from 100 rupees per hour. The park around it has a walkway and its well maintained. So can take a saunter stroll along the area’s 5 km path. Lot of flowers between walking paths given extra attraction to the park and also small restaurants are situated one side of the park.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "Entrance fee : 20 LKR\nBicycle Ride : 100 LKR / hour\nSwan-Shaped Boat Ride : 500 LKR/ 30 Minutes\nPony Ride : 300 LKR / 15 Minutes",
			"Ticket Value - Foriegner": "Entrance Fee : 200 LKR\nBicycle Ride : 100 LKR / hour\nSwan-Shaped Boat Ride : 500 LKR/ 30 Minutes\nPony Ride : 300 LKR / 15 Minutes",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "08:00 a.m. to 06:00 p.m."
		},
		{
			"type": "Place to Visit",
			"label": "Victoria Park",
			"Type" : "Nature and WildLife",
			"SubCategory": "Botanical Gardens and Parks",
			"Province": "Central Province",
			"District": "Nuwara Eliya District",
			"City": "Nuwara Eliya",
			"Address": "Badulla Rd, Nuwara Eliya 22200",
			"Contact No": "+94 522 222 275",
			"Description": "It is a nature park in the city with good scenic beauty. There is a miniature railway which is fun to ride. A river passes through the park, known as Nanu Oya River which increases the natural beauty of the park. It is a good place for bird-watching too. You will get to see some really beautiful birds like hornbills.",
			"VisitingDuration": "3 Hours",
			"Ticket Value - Local": "40 LKR",
			"Ticket Value - Foriegner": "300 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "7.00 a.m. to 7.00 p.m."
		},
		{
			"type": "Place to Visit",
			"label": "Kataragama Temple",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Hambantota District",
			"City": "Kataragama",
			"Address": "Main Office Ruhunu Maha Kataragama Dewalaya, Kataragama",
			"Contact No": "",
			"Description": "Kataragama is one of the holiest sites on the island most sacred to Buddhists and Hindus alike; pilgrims come here all year round to worship at the shrine of the god Kataragama. The temples come alive in the evenings when religious rituals take place as devotees arrive with trays of offerings to the god and where you’ll hear the sound of conch shells being blown and the beats of many drums.",
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 Hours Daily"
		},
		{
			"type": "Place to Visit",
			"label": "Yala National Park",
			"Type" : "Nature and WildLife",
			"SubCategory": ["Forests and Wild Life ","Safari"],
			"Province": "Southern Province",
			"District": "Hambantota District",
			"City": "Kataragama",
			"Address": "Yala National Park, Kirinda Rd, Kataragama",
			"Contact No": "+94 77 083 3772",
			"Description": "Yala National Park is Sri Lanka's most popular wildlife park due to the presence of many leopards.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "According to the Package",
			"Ticket Value - Foriegner": "According to the Package",
			"Wheel Chair Entry": "True",
			"Accesibility by Vehicle": "True",
			"Opened Hours": "9.00 a.m. - 4.00 p.m."
		},
		{
			"type": "Place to Visit",
			"label": "Mulkirigala Rock Temple",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Southern Province",
			"District": "Hambantota District",
			"City": "Tangalle",
			"Address": "Mulkirigala",
			"Contact No": "+94 72 531 7692",
			"Description": "Mulkirigala Raja Maha Vihara is an ancient Buddhist temple in Mulkirigala, Sri Lanka. It has been built on a 205 m high natural rock, surrounded with another four rocks known as Benagala, Kondagala, Bisogala and Seelawathiegala.",
			"VisitingDuration": "0.45 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "24 Hours Daily"
		},
		
		{
			"type": "Place to Visit",
			"label": "Sigiriya Rock Fortress",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Sigiriya",
			"Address": "Sigiriya, Sri Lanka",
			"Contact No": "",
			"Description": "Sigiriya is an ancient rock fortress and palace built by King Kashyapa during the reign of 473 – 495 which is standing majestically 660 feet straight up. It is located in the northern Matale district near the town of Dambulla in central province of Sri Lanka. The word Sigiriya or the Sinhagiri means the Lion’s Rock where you have to climb up 1200 steps before you reach the Lion Rock Fortress on top of Sigiriya. There are several platforms that break up the steps and allow for a little break if you need it. Today Sigiriya rock fortress is one of the most famous Archeological Treasure and UNESCO named Sigiriya rock as a World Heritage in 1982 under the name “Ancient City of Sigiriya Sri Lanka",
			"VisitingDuration": "3 Hours",
			"Ticket Value - Local": "50 LKR",
			"Ticket Value - Foriegner": "5000 LKR",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "From 7.00 a.m. to 5.30 p.m. every day. Last Entrance at 5.00 p.m"
		},
		{
			"type": "Place to Visit",
			"label": "Pidurangala Temple",
			"Type" : "Historical and Heritage",
			"SubCategory": "",
			"Province": "Central Province",
			"District": "Matale District",
			"City": "Sigiriya",
			"Address": "Pidurangala Royal Cave Temple, Sigiriya",
			"Contact No": "",
			"Description": "Pidurangala is a massive rock formation located a few kilometres north of Sigiriya in Sri Lanka. It has an interesting history closely related to that of the Sigiriya Rock Fortress. Being less grand and far more difficult to climb it is often overlooked by tourists. The Pidurangala area has been occupied on and off for over two thousand five hundred years by monks who lived in the caves around the site. It really came into prominence when King Kasyapa (477- 495 AD), who built Sigiriya, moved monks living around Sigiriya Rock to a newly refurbished and enlarged temple and monastery here at Pidurangala.",
			"VisitingDuration": "4 Hours",
			"Ticket Value - Local": "Free",
			"Ticket Value - Foriegner": "Free",
			"Wheel Chair Entry": "No",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "From 8.30 a.m. to 5.30 p.m. every day. Last Entrance at 5.00 p.m."
		},
		{
			"type": "Place to Visit",
			"label": "Ambuluwawa Temple",
			"Type" : "Historical and Heritage",
			"SubCategory" : "",
			"Province": "Central Province",
			"District": "Kandy District",
			"City": "Ambuluwawa",
			"Address": "Ambuluwawa Trigonometrical Station, Ambuluwaawa ICC Road, Gampola",
			"Contact No": "+94-387538880",
			"Description": "Ambuluwawa, located in Gampola, Kandy, is a biodiversity complex and Sri Lanka's first multi-religious center. There is a tall freestanding tower resembling a stylized Buddhist stupa, a Hindu Kovil, a Muslim mosque, and a Christian Church in this Trigonometrical Station. The tower rises to a height of approximately 48 meters (3567 feet) that you can reach the top of the fairy-tale-looking Ambuluwawa tower with its crooked Burton-esque staircase. Then you can experience the most amazing 360-degree views of the surrounding mountains, forests, rivers, and towns. Sometimes the view can be covered by the continuous mist.", 
			"VisitingDuration": "2 Hours",
			"Ticket Value - Local": "50 LKR",
			"Ticket Value - Foriegner": "300 LKR",
			"Wheel Chair Entry": "Yes",
			"Accesibility by Vehicle": "Yes",
			"Opened Hours": "8.30 a.m. to 5.00 p.m. Daily"
		}
	]
}